# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPyFEiRKEbcm_91G1qW2Ymn5h5KqJ9xY
"""

# Distance Calculator Program

KILOMETERS_TO_MILES = 0.621371   # Conversion factor from kilometers to miles
distance_km = float(input("Enter distance in kilometers: "))  # Ask the user for a distance in kilometers
distance_miles = distance_km * KILOMETERS_TO_MILES  # Convert kilometers to miles

print("Distance in miles:", distance_miles) # Display the converted distance
choice = input("Do you want to convert another distance? (yes/no): ") # Ask if the user wants to convert another distance

if choice == "yes":
    another_distance_km = float(input("Enter distance in kilometers: "))  # Ask for another distance in kilometers
    another_distance_miles = another_distance_km * KILOMETERS_TO_MILES  # Convert the second distance to miles
    print("Distance in miles:", another_distance_miles) # Display the second converted distance

else:
    print("Program ended.")  # End the program if the user does not want another conversion